name: top_stories_nyt
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  retrofit: ^4.0.3
  logger: any
  freezed: ^2.2.0
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.1
  flutter_bloc: ^8.1.1
  dio: ^5.3.3
  http: ^1.1.0
  go_router: ^12.0.1
  loading_gifs: ^0.3.0
  cached_network_image: ^3.2.2
  sqflite: ^2.2.0+3
  webview_flutter: ^4.4.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  retrofit_generator: ^8.0.3
  json_serializable: '>4.4.0'
  flutter_test:
    sdk: flutter

  test: ^1.21.4
  build_runner: ^2.3.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/placeholder_image/
    - images/